version: 1.0.{build}
build:
  verbosity: minimal
  project: VendingMachineEmulator.sln

deploy:
  - provider: Webhook
    url: https://discordapp.com/api/webhooks/280394698097426434/Y0p20s8TyXoCPeYenRl8QdAGy7dy2nW9ue_cDXwL3r0zOJQQGpQlxdCvjotYUlPNXtL8
