version: 1.0.{build}

branches:
  only:
    - master
    - develop

  # except:
  #   - playground

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
    - platform: x64

platform:
  - x86
  - x64

build:
  verbosity: minimal
  project: VendingMachineEmulator.sln
