version: 1.0.{build}

branches:
  only:
    - master
    - develop

  # except:
  #   - playground

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

platform:
  - x86
  - x64

build:
  verbosity: minimal
  project: VendingMachineEmulator.sln
  parallel: true # enable MSBuild parallel builds

notifications:
  - provider: Webhook
    url: https://discordapp.com/api/webhooks/280394698097426434/Y0p20s8TyXoCPeYenRl8QdAGy7dy2nW9ue_cDXwL3r0zOJQQGpQlxdCvjotYUlPNXtL8/appveyor
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
